# Generated by Django 4.2.19 on 2025-03-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_delete_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('atomic_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('atomic_mass', models.CharField(max_length=20)),
                ('cpk_hex_color', models.CharField(blank=True, max_length=6, null=True)),
                ('electron_configuration', models.CharField(blank=True, max_length=50, null=True)),
                ('electronegativity', models.CharField(blank=True, max_length=10, null=True)),
                ('atomic_radius', models.CharField(blank=True, max_length=10, null=True)),
                ('ionization_energy', models.CharField(blank=True, max_length=10, null=True)),
                ('electron_affinity', models.CharField(blank=True, max_length=10, null=True)),
                ('oxidation_states', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_state', models.CharField(blank=True, max_length=20, null=True)),
                ('melting_point', models.CharField(blank=True, max_length=20, null=True)),
                ('boiling_point', models.CharField(blank=True, max_length=20, null=True)),
                ('density', models.CharField(blank=True, max_length=20, null=True)),
                ('group_block', models.CharField(blank=True, max_length=30, null=True)),
                ('year_discovered', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
