# Generated by Django 4.2.19 on 2025-03-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='group_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='period_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='atomic_mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='atomic_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='atomic_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='boiling_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='electron_affinity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='electron_configuration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='electronegativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='group_block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='ionization_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='melting_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='standard_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='year_discovered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
