# Generated by Django 4.2.19 on 2025-03-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
