# Generated by Django 4.2.19 on 2025-03-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
